instance_type       = "t2.medium"
key_name            = "towerkey"
ami                 = "ami-0ff760d16d9497662"    #Use Centos7  image
vpc_id              = "vpc-6b445a0d"
user                = "centos"
ssh_key_location    = "~/.ssh/id_rsa"            #Import key pair to aws as "terraform"
zone_id             = "Z1NSGWEPJFDNW"            #Add hosted DNS zone ID here
domain              = "burakkarakas.net"
region              = "eu-west-1"
